import { randomBytes } from "crypto";
import { existsSync, readFileSync, appendFileSync, writeFileSync } from "fs";
import { join } from "path";

const SECRET_LENGTH = 32;
const ENV_KEY = "AUTH_SECRET";

/**
 * Ensure AUTH_SECRET is available in process.env.
 * If not set, auto-generate a random secret and persist it to .env.
 * Called once at application startup.
 */
export function ensureAuthSecret(): void {
  if (process.env[ENV_KEY]) return;

  const envPath = join(process.cwd(), ".env");

  // Try to read existing .env file for a previously generated secret
  if (existsSync(envPath)) {
    const content = readFileSync(envPath, "utf-8");
    const match = content.match(/^AUTH_SECRET="?([^"\n]+)"?/m);
    if (match?.[1]) {
      process.env[ENV_KEY] = match[1];
      return;
    }
  }

  // Generate new secret
  const secret = randomBytes(SECRET_LENGTH).toString("hex");
  process.env[ENV_KEY] = secret;

  // Persist to .env
  try {
    const line = `\n# Auto-generated by Dominion Dashboard (do not delete)\nAUTH_SECRET="${secret}"\n`;
    if (existsSync(envPath)) {
      appendFileSync(envPath, line);
    } else {
      writeFileSync(envPath, line);
    }
    console.info(
      "[dominion] AUTH_SECRET auto-generated and saved to .env. " +
      "For production, you may set it explicitly via environment variable."
    );
  } catch (err) {
    console.warn("[dominion] Could not persist AUTH_SECRET to .env:", err);
  }
}
