/**
 * Auto-generates src/plugins/community/index.ts by scanning community plugin folders.
 *
 * Each community plugin at src/plugins/community/{name}/index.ts MUST export:
 *   export const plugin: AppPlugin = { ... };
 *
 * And MAY optionally export:
 *   export const widget: ComponentType<WidgetProps> | null = null;
 *   export const widgetName: string | null = null;
 *
 * Run: npm run generate:plugins
 */

import * as fs from "fs";
import * as path from "path";

const ROOT = path.resolve(__dirname, "..");
const COMMUNITY_DIR = path.join(ROOT, "src", "plugins", "community");
const OUTPUT_FILE = path.join(COMMUNITY_DIR, "index.ts");

interface PluginEntry {
  dirName: string;       // e.g. "opnsense"
  camelName: string;     // e.g. "opnsense"
  hasWidget: boolean;
  hasWidgetName: boolean;
}

/** Convert a kebab-case directory name to camelCase. */
function toCamelCase(name: string): string {
  return name.replace(/-([a-z0-9])/g, (_, ch) => ch.toUpperCase());
}

/** Scan community plugin directories and detect exports. */
function discoverPlugins(): PluginEntry[] {
  if (!fs.existsSync(COMMUNITY_DIR)) {
    return [];
  }

  const entries = fs.readdirSync(COMMUNITY_DIR, { withFileTypes: true });
  const plugins: PluginEntry[] = [];

  for (const entry of entries) {
    // Only look at directories, skip index.ts and .gitkeep
    if (!entry.isDirectory()) continue;

    const indexPath = path.join(COMMUNITY_DIR, entry.name, "index.ts");
    if (!fs.existsSync(indexPath)) continue;

    const content = fs.readFileSync(indexPath, "utf-8");

    // Verify it exports a plugin
    if (!/export\s+const\s+plugin\b/.test(content)) {
      console.warn(`  Warning: ${entry.name}/index.ts does not export 'plugin', skipping.`);
      continue;
    }

    const hasWidget = /export\s+const\s+widget\b/.test(content);
    const hasWidgetName = /export\s+const\s+widgetName\b/.test(content);

    plugins.push({
      dirName: entry.name,
      camelName: toCamelCase(entry.name),
      hasWidget,
      hasWidgetName,
    });
  }

  // Sort alphabetically for deterministic output
  plugins.sort((a, b) => a.dirName.localeCompare(b.dirName));

  return plugins;
}

/** Generate the barrel file content. */
function generateBarrel(plugins: PluginEntry[]): string {
  const lines: string[] = [];

  // Header
  lines.push("// AUTO-GENERATED by scripts/generate-community-plugins.ts");
  lines.push("// Run: npm run generate:plugins");
  lines.push("// Do not edit manually — changes will be overwritten.");
  lines.push("");

  lines.push('import type { AppPlugin } from "../types";');
  lines.push('import type { ComponentType } from "react";');

  if (plugins.length === 0) {
    lines.push("");
    lines.push("export const communityPlugins: AppPlugin[] = [];");
    lines.push("export const communityWidgets: Record<string, ComponentType<unknown>> = {};");
    lines.push("");
    return lines.join("\n");
  }

  lines.push("");

  // Plugin imports
  for (const p of plugins) {
    lines.push(`import { plugin as ${p.camelName}Plugin } from "./${p.dirName}";`);
  }

  // Widget imports (only for plugins that export both widget and widgetName)
  const widgetPlugins = plugins.filter((p) => p.hasWidget && p.hasWidgetName);
  for (const p of widgetPlugins) {
    lines.push(
      `import { widget as ${p.camelName}Widget, widgetName as ${p.camelName}WidgetName } from "./${p.dirName}";`
    );
  }

  lines.push("");

  // communityPlugins array
  const pluginNames = plugins.map((p) => `${p.camelName}Plugin`);
  lines.push("export const communityPlugins: AppPlugin[] = [");
  for (const name of pluginNames) {
    lines.push(`  ${name},`);
  }
  lines.push("];");

  lines.push("");

  // communityWidgets map
  if (widgetPlugins.length === 0) {
    lines.push("export const communityWidgets: Record<string, ComponentType<unknown>> = {};");
  } else {
    lines.push("// Build widget map from plugins that export a widget + widgetName.");
    lines.push("// Entries with null widget/widgetName are filtered out at runtime.");
    lines.push("const _widgets: [string | null, ComponentType<unknown> | null][] = [");
    for (const p of widgetPlugins) {
      lines.push(`  [${p.camelName}WidgetName, ${p.camelName}Widget as ComponentType<unknown> | null],`);
    }
    lines.push("];");
    lines.push("");
    lines.push("export const communityWidgets: Record<string, ComponentType<unknown>> = {};");
    lines.push("for (const [name, component] of _widgets) {");
    lines.push("  if (name && component) {");
    lines.push("    communityWidgets[name] = component;");
    lines.push("  }");
    lines.push("}");
  }

  lines.push("");
  return lines.join("\n");
}

// ─── Main ─────────────────────────────────────────────────────────────────────

console.log("Scanning community plugins...");
const plugins = discoverPlugins();

if (plugins.length === 0) {
  console.log("  No community plugins found.");
} else {
  console.log(`  Found ${plugins.length} plugin(s): ${plugins.map((p) => p.dirName).join(", ")}`);
}

const content = generateBarrel(plugins);
fs.writeFileSync(OUTPUT_FILE, content, "utf-8");
console.log(`Generated: ${path.relative(ROOT, OUTPUT_FILE)}`);
