// AUTO-GENERATED by scripts/generate-community-plugins.ts
// Run: npm run generate:plugins
// Do not edit manually — changes will be overwritten.

import type { AppPlugin } from "../types";
import type { ComponentType } from "react";

export const communityPlugins: AppPlugin[] = [];
export const communityWidgets: Record<string, ComponentType<unknown>> = {};
